version: '3.4'

services:

  client1:
    image: redisapi
    build:
      context: .
      dockerfile: RedisApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Client1
    ports:
      - "5100:80"

  client2:
    image: redisapi
    build:
      context: .
      dockerfile: RedisApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Client2
    ports:
      - "5101:80"

