apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api-deployment
  namespace: redis
  labels:
    app: redis-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: redis-api
  template:
    metadata:
      labels:
        app: redis-api
    spec:
      containers:
        - name: redis-api
          image: drgreen28/redisapi:1.0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          args:
            - --auto-generate-certificates
---
apiVersion: v1
kind: Service
metadata:
  name: redis-api-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: redis-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
spec:
  defaultBackend:
    service:
      name: redis-api-service
      port:
        number: 80
  rules:
  - host: ingress.local
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name:  redis-api-service
            port: 
              number: 80